# Generated by Django 4.2.16 on 2026-02-13 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, default='', max_length=64)),
                ('bio', models.TextField(blank=True, default='')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/')),
                ('show_email', models.BooleanField(default=False, verbose_name='公开邮箱')),
                ('profile_visible', models.CharField(choices=[('all', '所有人'), ('login', '仅登录用户'), ('self', '仅自己')], default='all', max_length=20, verbose_name='资料可见性')),
                ('email_on_reply', models.BooleanField(default=True, verbose_name='回复时邮件通知')),
                ('email_on_mention', models.BooleanField(default=True, verbose_name='被@时邮件通知')),
                ('timezone', models.CharField(default='Asia/Shanghai', max_length=64)),
                ('language', models.CharField(default='zh-hans', max_length=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户资料',
                'verbose_name_plural': '用户资料',
                'db_table': 'user_profiles',
            },
        ),
    ]
