# Generated by Django 4.2.16 on 2026-02-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=64)),
                ('action', models.CharField(max_length=32)),
                ('target', models.CharField(default='', max_length=255)),
                ('target_id', models.PositiveIntegerField(default=0)),
                ('ip_address', models.CharField(default='', max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'admin_logs',
                'ordering': ['-id'],
            },
        ),
    ]
