# Generated by Django 4.2.16 on 2026-02-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('value', models.TextField(default='')),
                ('category', models.CharField(default='general', max_length=32)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '站点设置',
                'verbose_name_plural': '站点设置',
                'db_table': 'site_settings',
            },
        ),
    ]
