# Generated by Django 4.2.16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0004_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='content_is_html',
            field=models.BooleanField(default=False, help_text='内容为 HTML 时勾选，否则按换行显示'),
        ),
    ]
