# Generated by Django 4.2.16 on 2026-02-14 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0005_page_content_is_html'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('url', models.URLField(max_length=512)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_visible', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '友情链接',
                'verbose_name_plural': '友情链接',
                'db_table': 'links',
                'ordering': ['order', 'id'],
            },
        ),
    ]
