# Generated by Django 4.2.16 on 2026-02-14 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0006_add_comment_viewcount_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '邮件订阅',
                'verbose_name_plural': '邮件订阅',
                'db_table': 'newsletter_subscribers',
            },
        ),
    ]
