# Generated by Django 4.2.16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bbspost',
            name='approved',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
